[build]
  base = "Frontend"
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://togglenest-db.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200